I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 43, in script
    m "suh dude"
Exception: Sayer 'm' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 43, in script
    m "suh dude"
  File "/Users/anishtoomu/Downloads/code/renpy-7.3.5-sdk/renpy/ast.py", line 678, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/anishtoomu/Downloads/code/renpy-7.3.5-sdk/renpy/ast.py", line 576, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'm' is not defined.

Darwin-18.7.0-x86_64-i386-64bit
Ren'Py 7.3.5.606
ssbmSim 1.0
Mon Jan 13 09:06:51 2020
